<?php

namespace App\FormsPlus;

use Illuminate\Support\Facades\File;
use Statamic\Facades\YAML;

class StylesManager
{
    protected static function path(): string
    {
        return storage_path('forms-plus/styles.yaml');
    }

    public static function get(): array
    {
        $path = static::path();

        $saved = File::exists($path)
            ? (YAML::parse(File::get($path)) ?? [])
            : [];

        return array_merge(static::defaults(), $saved);
    }

    public static function save(array $styles): void
    {
        $path = static::path();
        File::ensureDirectoryExists(dirname($path));
        File::put($path, YAML::dump(array_intersect_key($styles, static::defaults())));
    }

    public static function defaults(): array
    {
        return [
            'css'                => '',
            'preview_stylesheet' => '',
        ];
    }

    public static function writeCssSourceFile(string $css): void
    {
        $path = resource_path('css/forms-plus.css');

        if (trim($css) === '') {
            if (File::exists($path)) {
                File::delete($path);
            }
            return;
        }

        File::put($path, "/* Generated by Forms Plus — edit in the CP Theme editor, not here */\n" . $css);
    }

    public static function injectImport(string $targetPath): bool
    {
        if (! File::exists($targetPath)) {
            return false;
        }

        $content = File::get($targetPath);

        if (str_contains($content, 'forms-plus.css')) {
            return false;
        }

        // Insert after @import "tailwindcss" so Tailwind processes it in the right order
        if (preg_match('/@import\s+["\']tailwindcss["\']/', $content)) {
            $updated = preg_replace(
                '/(@import\s+["\']tailwindcss["\'][^;]*;)/u',
                "$1\n@import './forms-plus.css'; /* forms-plus */",
                $content,
                1
            );
        } else {
            $updated = "@import './forms-plus.css'; /* forms-plus */\n" . $content;
        }

        File::put($targetPath, $updated);

        return true;
    }

    public static function resolvePreviewStylesheetPath(string $url): ?string
    {
        if (! str_starts_with($url, '/css/')) {
            return null;
        }

        $relative = substr($url, strlen('/css/'));
        $dir      = realpath(resource_path('css'));
        $path     = realpath(resource_path('css/' . $relative));

        if (! $path || ! $dir || ! str_starts_with($path, $dir . DIRECTORY_SEPARATOR)) {
            return null;
        }

        return $path;
    }

    public static function renderStyles(): string
    {
        if (request()->attributes->get('fp_styles_rendered')) {
            return '';
        }
        request()->attributes->set('fp_styles_rendered', true);

        $css = trim(static::get()['css'] ?? '');

        if ($css === '') {
            return '';
        }

        return '<style>' . $css . '</style>';
    }
}
